tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "awscli"
brew "fzf"
brew "mysql"
brew "postgresql"
brew "tree"
brew "vim", args: ["with-override-system-vi"]
brew "watchman"
cask "brave-browser"
cask "expressvpn"
cask "iina"
cask "insomnia"
cask "visual-studio-code"
